### ISSUE TITLE
コメント

### ISSUE THREAD

**Issue by c0b21093** [c0b21127/ProjExD#12]
https://github.com/c0b21127/ProjExD/blob/2a6aa3a7df16c0e389b34381b2a3db1835c2f99f/ex04/dodge_bomb.py#L60
自分も爆弾の加速をやったのですがvx、vyを直接書き換えるとバグってしまったのですが、ちゃんと動作しているそうなので勉強になりました。

**Comment by c0b21127** [comment]
ありがとうございます。精進します。
